### ISSUE TITLE
请问怎么使用codelab通过蓝牙连接实物呢？有相关示例么

### ISSUE THREAD

**Issue by chrislinbo1224** [Scratch3Lab/codelab-adapter-docs#71]

**Comment by wwj718** [comment]
目前有两个通过蓝牙串口串口的例子(由 乐聚机器人 维护)

*  [extension_leju_aelosedu.py](https://github.com/CodeLabClub/codelab_adapter_extensions/blob/master/extensions_v2/extension_leju_aelosedu.py)
*  [extension_aelosedu_online.py](https://github.com/CodeLabClub/codelab_adapter_extensions/blob/master/extensions_v2/extension_aelosedu_online.py)

如果是使用ble，可以使用[pygatt](https://github.com/peplin/pygatt)，已经内置在adapter里
