### ISSUE TITLE
为何开启wechat，没有二维码弹窗呢？

### ISSUE THREAD

**Issue by dellaxing** [Scratch3Lab/codelab-adapter-docs#74]
本人是使用codelab-adapter 3.5.1版本，多次尝试也无法成功开启微信扩展，只有一次有弹出qrcode界面，但用微信扫描登录后没有任何反应，请问这是什么问题，我使用macos10.15.6，chrome_84.0.4147.135

**Comment by wwj718** [comment]
可以先尝试一下 网页微信：https://wx.qq.com/（目前许多账号被腾讯限制使用网页微信）

如果网页微信正常，则扫码之后（手机会显示网页登陆成功），即可使用相应积木

**Comment by dellaxing** [comment]
error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
试了一下，扫码以后，浏览器显示以上提示。。。。。
按这说法，我就不能使用微信的积木了？

**Comment by wwj718** [comment]
是的
